import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "Lead Lev AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <ClerkProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </ClerkProvider>
    </html>
  );
}
